Trialization
kabilar/workflow-miniscope pull request #4
Opened 2022-04-27 20:32 UTC by CBroz1

Added
- Trial data files
- ingestion functions first pass - needs testing bc element-interface version did not include `allow_direct_insert` arg
- `analysis.py` script for downstream analysis - needs testing, not yet run

Needs
- integration tests - Nice to have

Notes
- I have the following in my `.bash_profile` to expedite jupytext process, which motivated the `scripts/` -> `py_scripts/` rename
  ```bash
  alias jupysync='jupytext --sync notebooks/0*ipynb; mv notebooks/*py notebooks/py_scripts'
  ```

2022-04-28 16:49 UTC, CBroz1 commented
Drafting notebooks 05 and 07 now

2022-04-28 19:02 UTC, CBroz1 commented
@kabilar - ran most of both notebook 05 and 07, but ran into errors in each case where miniscope doesn't match structure from calcium imaging. If you use the `u24_` prefix on `dss-db`, you can pick up where I left off.

05 error:
```python
average_image = (miniscope.MotionCorrection.Summary & curation_key
                ).fetch1('average_image')
plt.imshow(average_image);
# ---
TypeError: Invalid shape (1, 600, 600) for image data
```

07 error
```python
analysis.ActivityAlignment.populate(display_progress=True)
# ---
UnknownAttributeError: Unknown column 'mask' in 'order clause'
```

2022-04-29 23:27 UTC, ttngu207 requested changes

2022-04-29 23:27 UTC, ttngu207 commented on workflow_miniscope/analysis.py
> +                                                              'nframes', 'fps')
```suggestion
        # DEVNOTE : caimg->miniscope, no scan_datetime. so removed scan_time from fetch
        #           safe to assume no sess-scan diff?
        sess_time, rec_time, nframes, frame_rate = (miniscope.RecordingInfo
                                                     * session.Session
                                                     & key
                                                     ).fetch1('session_datetime',
                                                              'recording_datetime',
                                                              'nframes', 'fps')
```

2022-04-29 23:27 UTC, ttngu207 commented on workflow_miniscope/analysis.py
> +        scan_time = None # BEING ADDED TO ELEMENT
```suggestion
```

2022-04-29 23:27 UTC, ttngu207 commented on workflow_miniscope/analysis.py
> +
```suggestion
        rec_start = (rec_time - sess_time).total_seconds() if rec_time else 0
        frame_timestamps = np.arange(nframes) / frame_rate + rec_start

```

2022-04-30 05:53 UTC, merged

2022-04-30 05:53 UTC, kabilar commented
Hi @CBroz1, just a heads up, I made the mistake of directly committing Thinh's suggestions to your fork/branch.

2022-04-30 05:58 UTC, kabilar commented
Thank you for these updates, @CBroz1!

2022-04-30 15:59 UTC, kabilar commented
I removed trial 50 since the start time occurred before trials 47-49.